server:
  port: 8080

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        jdbc:
          batch_size: 100
        order_inserts: true
        generate_statistics: false
    show-sql: false
    hibernate:
      ddl-auto: none

parsing-settings:
  jsoup_referer: http://www.google.com
  jsoup_user-agent: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0
  redirect: true
  delay: 2000

indexing-settings:
  sites:
#    - url: https://www.lenta.ru
#      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://www.svetlovka.ru/
      name: Светловка
#    - url: https://et-cetera.ru/mobile/
#      name: Театр Et Cetera
#    - url: http://radiomv.ru/
#      name: Радио "Милицейская волна"
